### PR TITLE
Use commit hashes only

### LINKED ISSUE #17: Coverage is offset due to fetching wrong commit.
Compare this section of code in both the extension and in the Codecov UI. Coverage appears to be offset

## Extension
URL: https://github.com/codecov/codecov-cli/blob/master/codecov_cli/main.py

Screenshot 2023-05-12 at 8 46 46 AM

## Codecov UI
URL: https://app.codecov.io/gh/codecov/codecov-cli/blob/master/codecov_cli/main.py

Screenshot 2023-05-12 at 8 47 45 AM

## Problem

I believe the actual issue here is that GitHub is showing a commit that's ahead of the coverage being displayed because that coverage has not yet been uploaded to Codecov. you can see here that the commit in question`e76d9b9` is in a processing state on Codecov:

Screenshot 2023-05-12 at 8 52 59 AM
 
(Source: https://app.codecov.io/gh/codecov/codecov-cli/commit/e76d9b907c78c26a27899654bf094d021067378c)

I think the extension is just fetching the most recent coverage from the branch, which is `ec1c3ef` (link: https://app.codecov.io/gh/codecov/codecov-cli/commit/ec1c3ef82c9abc53ed1fecd74e340a7d4e5b202c). Therefore, the coverage is incorrect because we're overlaying coverage from a prior commit on top of more recent code. 

## Potential Solution

We should probably fail to fetch coverage if we cannot find coverage for the specific commit the user is trying to view in GitHub.

### LINKED ISSUE #40: Commit ref parsing is buggy
The commit ref for which to fetch the coverage report is currently parsed from the URL using a [regex](https://github.com/codecov/codecov-browser-extension/blob/0.3.2/src/content/github/file/main.tsx#L230).

This approach breaks for tags (or branches with `/` in name) because we can't tell where the ref ends.

### PR DESCRIPTION
**Pull request by anukul**
Fixes #17
Fixes #40

### CODE REVIEW

File: src/content/github/common/fetchers.ts [hunk 1]
```diff
@@ -1,84 +1,78 @@
 import browser from "webextension-polyfill";
-import { MessageType } from "src/types";
+import {
+  FileCoverageReportResponse,
+  FileMetadata,
+  MessageType,
+} from "src/types";
+
+export async function getMetadata(url: string): Promise<FileMetadata> {
+  const response = await fetch(url).then((response) => response.json());
```
Comment (scott-codecov) [inline src/content/github/common/fetchers.ts:9]: For this to work with private repos do we need to pass `credentials: 'include'` to `fetch`? (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included)

Comment (anukul) [reply src/content/github/common/fetchers.ts:9]: Works with the default value (same-origin)

**Review by eliatcodecov — APPROVED** [review]
